# Generated by Django 5.0.4 on 2024-05-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbiz_security', '0002_customerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.BooleanField(default=False, help_text='True or False: You and your employees can successfully spot a phishing email.')),
                ('Q2', models.IntegerField(help_text='How many of the following does your business have?: Strong passwords, Antivirus Software, Automatic Software Updates, and Backup(s) in place for data storage')),
                ('Q3', models.CharField(help_text='Yes or No: Does your business/organization have a cyber security plan and a ransomware plan?', max_length=3)),
            ],
        ),
    ]
