# Generated by Django 5.0.4 on 2024-05-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallbiz_security', '0004_resourcerequest_surveydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='ReqLink',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='ReqResourceName',
            new_name='Resource_Name',
        ),
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='ReqSourceName',
            new_name='Source_Name',
        ),
    ]
