# Generated by Django 5.0.4 on 2024-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbiz_security', '0005_rename_reqlink_resourcerequest_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Q1',
            field=models.BooleanField(default=False, help_text='True or False (Check if true): You and your employees can successfully spot a phishing email.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q2',
            field=models.IntegerField(help_text='0 to 4: How many of the following does your business have? Strong passwords, Antivirus Software, Automatic Software Updates, and Backup(s) in place for data storage'),
        ),
    ]
